apps/database/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as django_views
from . import views
from apps.database.views import CharacterNew

urlpatterns = [
    url(r'^$', views.start, name='start'),
    url(r'^campaigns$', views.campaign_list, name='campaign_list'),
    url(r'^campaigns/(?P<pk>\d+)/characters/$', views.campaign_character_list,
        name='campaign_character_list'),
    url(r'^campaigns/(?P<pk>\d+)/$',
        views.campaign_detail, name='campaign_detail'),
    url(r'^characters/(?P<pk>\d+)/pokemon/$', views.character_pokemon_list,
        name='character_pokemon_list'),
    url(r'^characters/(?P<pk>\d+)/pets/$', views.character_pet_list,
        name='character_pet_list'),
    url(r'^characters/(?P<pk>\d+)/$', views.character_detail,
        name='character_detail'),
    url(r'^pets/(?P<pk>\d+)/$', views.pet_detail, name='pet_detail'),
    url(r'^pets/(?P<pk>\d+)/edit/$', views.PetEdit.as_view(),
        name='pet_edit'),
    url(r'^pets/new/$', views.PetNew.as_view(),
        name='pet_new'),
    url(r'^characters/new/$', views.CharacterNew.as_view(),
        name='character_new'),
    url(r'^characters/(?P<pk>\d+)/edit/$', views.CharacterEdit.as_view(),
        name='character_edit'),
    url(r'^npc/new/$', views.NPCNew.as_view(), name='npc_new'),
    url(r'^campaigns/(?P<pk>\d+)/pokemon/$', views.campaign_pokemon_list,
        name='campaign_pokemon_list'),
    url(r'^campaigns/(?P<pk>\d+)/npcs/$', views.campaign_npc_list,
        name='campaign_npc_list'),
    url(r'^pokemon/(?P<pk>\d+)/$', views.pokemon_detail,
        name='pokemon_detail'),
    url(r'^pokemon/new/$', views.PokemonNew.as_view(), name='pokemon_new'),
    url(r'^pokemon/(?P<pk>\d+)/edit/$', views.PokemonEdit.as_view(),
        name='pokemon_edit'),
    url(r'^campaigns/new/$', views.CampaignNew.as_view(), name='campaign_new'),
    url(r'^campaigns/(?P<pk>\d+)/edit/$', views.CampaignEdit.as_view(),
        name='campaign_edit'),
    url(r'^players/(?P<pk>\d+)/$', views.player_detail, name='player_detail'),
    url(r'^about/$', views.about, name='about'),
    url(r'^accounts/login/$', django_views.login, name='login'),
    url(r'^accounts/logout/$', django_views.logout,
        name='logout', kwargs={'next_page': '/campaigns'}),
    # Registration URLs
    url(r'^accounts/register/$', views.Register.as_view(), name='register'),
    url(r'^accounts/register/complete/$',
        views.registration_complete,
        name='registration_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dally_stats/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', include('smuggler.urls')),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'', include('stally.urls')),
]

mwm-db/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.flatpages import views

urlpatterns = [
    # url(r'^admin/', include('smuggler.urls')),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'', include('apps.database.urls')),
    url(r'^pages/', include('django.contrib.flatpages.urls')),

    # Flatpages
    url(r'^contributor-guidelines-1/$', views.flatpage,
        {'url': '/contributor-guidelines-1/'}, name='guidelines-1'),
    url(r'^contributor-guidelines-2/$', views.flatpage,
        {'url': '/contributor-guidelines-2/'}, name='guidelines-2'),
    url(r'^contributor-guidelines-3/$', views.flatpage,
        {'url': '/contributor-guidelines-3/'}, name='guidelines-3'),
    url(r'^contributor-guidelines-4/$', views.flatpage,
        {'url': '/contributor-guidelines-4/'}, name='guidelines-4'),
]

apps/database/models.py
# This Python file uses the following encoding: utf-8

from django.urls import reverse
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.validators import validate_comma_separated_integer_list
from datetime import timedelta
from .myFields import DayOfTheWeekField


class BaseModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE,
                                   related_name='%(class)s_created',
                                   null=True, blank=True, default=None)
    modified_by = models.ForeignKey(User, on_delete=models.CASCADE,
                                    related_name='%(class)s_modified',
                                    null=True, blank=True, default=None)

    class Meta:
        abstract = True


class Player(BaseModel):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/players/',
                              default='images/no-img.jpg')

    def main_characters(self):
        characters = Character.objects.filter(player=self)
        trainees = Trainee.objects.filter(player=self)
        campaigns = Campaign.objects.filter(dm=self)
        npcs = Character.objects.filter(campaign__in=campaigns)
        return characters.exclude(pk__in=trainees).exclude(pk__in=npcs)

    def __str__(self):
        return self.name

    def __lt__(self, other):
        return self.name < other.name

    def get_absolute_url(self):
        return reverse('player_detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['name']


class Campaign(BaseModel):
    name = models.CharField(max_length=200)
    dm = models.ForeignKey(Player, on_delete=models.PROTECT,
                           related_name='campaigns_dming', verbose_name='DM')
    start_date = models.DateField(default=timezone.now,
                                  verbose_name='Start date')
    image = models.ImageField(upload_to='images/campaigns/',
                              default='images/no-img.jpg')
    youtube_playlist = models.URLField(blank=True, null=True,
                                       verbose_name='YouTube playlist')
    streaming_channel = models.URLField(blank=True, null=True,
                                        verbose_name='Streamed on')
    schedule = DayOfTheWeekField(blank=True, null=True,
                                 verbose_name='Is played on')
    schedule_time = models.TimeField(blank=True, null=True, verbose_name='At')
    schedule_rythm = models.CharField(blank=True, null=True, max_length=1,
                                      choices=(
                                        ('1', 'weekly'),
                                        ('2', 'biweekly'),
                                        ('3', 'every three weeks'),
                                      ))
    genre = models.CharField(blank=True, null=True, max_length=100)
    system = models.CharField(blank=True, null=True, max_length=200)
    description = models.TextField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True,
                                verbose_name='End date')

    def players(self):
        characters = Character.objects.filter(campaign=self)
        return sorted(set(Player.objects.filter(
            characters__in=characters).exclude(name=self.dm.name)))

    def characters_without_trainees(self):
        characters = Character.objects.filter(
            campaign=self).exclude(pk__in=self.npcs())
        trainees = Trainee.objects.filter(campaign=self)

        return characters.exclude(pk__in=trainees)

    def pc_pokemon(self):
        return Pokemon.objects.filter(campaign=self).exclude(player=self.dm)

    def npcs(self):
        characters = Character.objects.filter(campaign=self)
        pokemon = Pokemon.objects.filter(campaign=self)
        return characters.filter(player=self.dm).exclude(pk__in=pokemon)

    def npc_pokemon(self):
        pokemon = Pokemon.objects.filter(campaign=self)
        return pokemon.filter(player=self.dm)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('campaign_detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['name']


class Session(BaseModel):
    name = models.CharField(max_length=200)
    date = models.DateField(default=timezone.now)
    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE,
                                 related_name='sessions')
    length = models.DurationField(default=timedelta(0))
    number = models.IntegerField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    players_present = models.ManyToManyField(Player, blank=True)

    def __str__(self):
        return "{}. {}".format(self.number, self.name)

    class Meta:
        ordering = ['name']


class URL(BaseModel):
    link = models.URLField()
    session = models.ForeignKey(Session, on_delete=models.CASCADE,
                                related_name='youtube_videos')


class Place(BaseModel):
    name = models.CharField(max_length=400)
    campaigns = models.ManyToManyField(Campaign)
    description = models.TextField(blank=True, null=True)


class Character(BaseModel):
    name = models.CharField(max_length=100)
    player = models.ForeignKey(Player, on_delete=models.PROTECT,
                               related_name='characters')
    campaign = models.ForeignKey(Campaign, on_delete=models.PROTECT,
                                 related_name='characters')
    character_class = models.CharField(max_length=200, blank=True, null=True,
                                       verbose_name='Class')
    image = models.ImageField(upload_to='images/characters/',
                              default='images/no-img.jpg')
    pronouns = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    lives_in = models.ManyToManyField(Place, blank=True,
                                      related_name='citizens')
    in_campaign_since = models.ForeignKey(Session, on_delete=models.SET_NULL,
                                          blank=True, null=True)

    def pokemons(self):
        return Pokemon.objects.filter(trainer=self)

    def pets(self):
        return Pet.objects.filter(trainer=self)

    def is_npc(self):
        return self.player == self.campaign.dm

    def __str__(self):
        if self.is_npc():
            return '{} (NPC)'.format(self.name)
        else:
            return '{} (played by {})'.format(self.name, self.player.name)

    def get_absolute_url(self):
        return reverse('character_detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['name']


class Trainee(Character):
    trainer = models.ForeignKey(
        Character, on_delete=models.SET_NULL, related_name='trainees',
        blank=True, null=True)

    class Meta:
        ordering = ['name']


class Pokemon(Trainee):
    pokedex_nr = models.CharField(
        max_length=7, blank=True, null=True,
        validators=[validate_comma_separated_integer_list],
        verbose_name='Pokédex number')
    type_p = models.CharField(max_length=200, verbose_name='Type')
    nature = models.CharField(max_length=200, blank=True, null=True)
    kind = models.CharField(max_length=200)

    def create_pokemon(character, name, pokedex_nr, type_p, nature, kind):
        new_pokemon = Pokemon(name=name, player=character.player,
                              campaign=character.campaign,
                              pokedex_nr=pokedex_nr,
                              trainer=character,
                              type_p=type_p, nature=nature, kind=kind)
        new_pokemon.save()

    def get_absolute_url(self):
        return reverse('pokemon_detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Pokémon'
        verbose_name_plural = 'Pokémon'


class Pet(Trainee):
        def get_absolute_url(self):
            return reverse('pet_detail', kwargs={'pk': self.pk})

apps/database/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Pokemon, Character, Pet, Campaign


class PokemonForm(forms.ModelForm):

    class Meta:
        model = Pokemon
        fields = ('image', 'name', 'player', 'campaign', 'pronouns',
                  'pokedex_nr', 'kind', 'type_p',
                  'trainer', 'nature', 'description')


class CampaignForm(forms.ModelForm):

    class Meta:
        model = Campaign
        fields = ('image', 'name', 'dm', 'start_date', 'youtube_playlist',
                  'streaming_channel', 'schedule', 'schedule_time',
                  'schedule_rythm', 'genre', 'system', 'description',
                  'end_date')


class CharacterForm(forms.ModelForm):

    class Meta:
        model = Character
        fields = ('image', 'name', 'player', 'campaign', 'pronouns',
                  'character_class', 'description')


class PetForm(forms.ModelForm):

    class Meta:
        model = Pet
        fields = ('image', 'name', 'player', 'trainer', 'campaign', 'pronouns',
                  'character_class', 'description')


class NPCForm(forms.ModelForm):

    class Meta:
        model = Character
        fields = ('image', 'name', 'campaign', 'pronouns',
                  'character_class', 'description')


class MyRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(MyRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.is_active = False

        if commit:
            user.save()

        return user

apps/database/templates/database/_campaign_attributes.html
<div class="date">
  <p><b>Started on:</b> {{ campaign.start_date }}</p>
</div>
<div class="row">
    <div class="col-md-4 col-md-push-8">
        <img class="portrait img-fluid"
           src="{{ campaign.image.url }}" alt="{{ campaign.name }} image">
   </div>
   <div class="col-md-8 col-md-pull-4">
      <p><b>DM:</b> <a href="{% url 'player_detail' pk=campaign.dm.pk %}">
          {{ campaign.dm }}</a></p>
      <p><b>Players:</b>
        {% for player in campaign.players %}
          <a href="{% url 'player_detail' pk=player.pk %}">{{ player }}</a>
        {% endfor %}
      </p>
      {% if campaign.genre %}
        <p><b>Genre:</b> {{ campaign.genre }}</p>
      {% endif %}
      {% if campaign.system %}
        <p><b>System:</b> {{ campaign.system }}</p>
      {% endif %}
      {% if campaign.schedule and campaign.schedule_rythm and campaign.schedule_time%}
        <p><b>Schedule:</b> {{ campaign.get_schedule_rythm_display }}
                            on {{ campaign.get_schedule_display }} at {{ campaign.schedule_time }}.</p>
      {% endif %}
      {% if campaign.streaming_channel %}
        <p><b>Streamed on:</b> <a target="_blank"
          href="{{ campaign.streaming_channel }}">
            {{ campaign.streaming_channel }}</a></p>
      {% endif %}
      {% if campaign.youtube_playlist %}
        <p><b>Uploaded to:</b>  <a target="_blank"
          href="{{ campaign.youtube_playlist }}">
            {{ campaign.youtube_playlist }}</a></p>
      {% endif %}
      <p><b>Description:</b> {{ campaign.description|linebreaksbr }}</p>
      {% if perms.database.change_campaign %}
        <a class="btn btn-default" href="{% url 'campaign_edit' pk=campaign.pk %}">
            <span class="glyphicon glyphicon-pencil"></span></a>
      {% endif %}
    </div>

</div>

apps/database/templates/database/_character_attributes.html
<div class="row">
  <div class="col-md-2 col-md-push-8">
    {% if not character.image.url == "/media/images/no-img.jpg" %}
      <img class="portrait img-fluid" src="{{ character.image.url }}"
         alt="{{ character.name }} image">
    {% endif %}
  </div>
  <div class="col-md-8 col-md-pull-2">
      {% if character.character_class %}
        <div class="class-text">
          <p>{{ character.character_class }}</p>
        </div>
      {% endif %}
      <p><b>Player:</b> <a href="{% url 'player_detail' pk=character.player.pk %}">
          {{ character.player.name }}</a></p>
      <p><b>Campaign: </b>
          <a href="{% url 'campaign_detail' pk=character.campaign.pk %}">
              {{ character.campaign }}</a></p>
      {% if character.pronouns %}
        <p><b>Pronouns:</b> {{ character.pronouns }}</p>
      {% endif %}
      {% if character.description %}
        <p><b>Description:</b> {{ character.description|linebreaksbr }}</p>
      {% endif %}
      {% if perms.database.change_character %}
        <a class="btn btn-default" href="{% url 'character_edit' pk=character.pk %}">
            <span class="glyphicon glyphicon-pencil"></span></a>
      {% endif %}
  </div>
</div>

apps/database/templates/database/_pet_attributes.html
<div class="row">
  <div class="col-md-2 col-md-push-8">
    {% if not pet.image.url == "/media/images/no-img.jpg" %}
      <img class="portrait img-fluid" src="{{ pet.image.url }}"
         alt="{{ pet.name }} image">
    {% endif %}
  </div>
  <div class="col-md-8 col-md-pull-2">
      {% if pet.character_class %}
        <div class="class-text">
          <p>{{ pet.character_class }}</p>
        </div>
      {% endif %}
      <p><b>Player:</b> <a href="{% url 'player_detail' pk=pet.player.pk %}">
          {{ pet.player.name }}</a></p>
      <p><b>Campaign: </b>
          <a href="{% url 'campaign_detail' pk=pet.campaign.pk %}">
              {{ pet.campaign }}</a></p>
      {% if pet.trainer %}
        <p><b>Trainer:</b> <a href="
            {% url 'character_detail' pk=pet.trainer.pk %}">
            {{ pet.trainer }}</a></p>
      {% endif %}
      {% if pet.pronouns %}
        <p><b>Pronouns:</b> {{ pet.pronouns }}</p>
      {% endif %}
      {% if pet.description %}
        <p><b>Description:</b> {{ pet.description|linebreaksbr }}</p>
      {% endif %}
      {% if perms.database.change_pet %}
        <a class="btn btn-default" href="{% url 'pet_edit' pk=pet.pk %}">
            <span class="glyphicon glyphicon-pencil"></span></a>
      {% endif %}
  </div>
</div>

apps/database/templates/database/_pokemon_attributes.html
<div class="row">
  <div class="col-md-2 col-md-push-8">
    {% if not pokemon.image.url == "/media/images/no-img.jpg" %}
      <img class="portrait img-fluid" src="{{ pokemon.image.url }}"
           alt="{{ pokemon.name }} image">
    {% endif %}
  </div>

  <div class="col-md-8 col-md-pull-2">
    <div class="class-text">
      <p>{{ pokemon.kind }}</p>
    </div>
    <p><b>Type:</b> {{ pokemon.type_p }}</p>
    {% if pokemon.pronouns %}
      <p><b>Pronouns</b> {{ pokemon.pronouns }}</p>
    {% endif %}
    {% if pokemon.trainer %}
      <p><b>Trainer:</b> <a href="
          {% url 'character_detail' pk=pokemon.trainer.pk %}">
          {{ pokemon.trainer }}</a></p>
    {% endif %}
    {% if pokemon.nature %}
      <p><b>Nature:</b> {{ pokemon.nature }}</p>
    {% endif %}
    {% if pokemon.description %}
      <p><b>Description:</b> {{ pokemon.description|linebreaksbr }}</p>
    {% endif %}
    {% if perms.database.change_pokemon %}
      <a class="btn btn-default" href="{% url 'pokemon_edit' pk=pokemon.pk %}">
          <span class="glyphicon glyphicon-pencil"></span></a>
    {% endif %}
  </div>
</div>

apps/database/templates/database/about.html
{% extends 'base.html' %}

{% block pagetitle %}
  About
{% endblock %}

{% block nav-about %}<strong class="nav-active">About</strong>{% endblock %}

{% block content %}
  <div class="page-title">
    <h1>About</h1>
  </div>

  <p>This website lists characters from various campaigns that are part of
    Mistakes were made, a network of role-playing games initiated by
    <a target="_blank" href="http://dallydaydream.tumblr.com/">Dally</a>.</p>
  <p>It was built by
      <a target="_blank" href="https://twitter.com/eyefox42">eyefox</a>
      using the
      <a target="_blank" href="https://www.djangoproject.com/">
          Django framework</a>.
      The source code is available on
      <a target="_blank" href="https://github.com/eyefox47/mvm.db">
          GitHub</a>.</p>

  <h2>Licensing</h2>
  <ul>
    <li>Some of the images for Pokemon are copyrighted and taken from
      <a href="http://www.pokemon.co.jp/">http://www.pokemon.co.jp/</a>
      under fair use.</li>
  </ul>
{% endblock %}

apps/database/templates/database/campaigns_list_items.html
{% for campaign in campaigns %}
  <li><a href="{% url 'campaign_detail' pk=campaign.pk %}">{{ campaign.name }}</a></li>
{% endfor %}

apps/database/templates/database/contributor_guidelines.html
{% extends 'base.html' %}

{% block pagetitle %}
  Contributor guidelines
{% endblock %}

{% block content %}
  <h1>Contributor guidelines</h1>
  <p>First of all, thank you so much for willing to help fill this database.
    I want to stress that whatever little you can do to add and improve the
    information about the many RPs that are represented by MWM, would be of
    great help.
    The guidelines are merely here to give you an idea about where you could
    put what information and how a description could look like.
  </p>

  <h2>Campaigns</h2>
  <p></p>
{% endblock %}

apps/database/templates/database/start.html
{% extends 'base.html' %}

{% block pagetitle %}
  Home
{% endblock %}

{% block content %}
    <div class="jumbotron">
        <div class="container">
            <h1>Welcome to <br>Mistakes Were Made...DB!</h1>
            <p>This website is meant to serve as an overview for the role-playing
                campaigns streamed by <a target="_blank" href="http://dallydaydream.tumblr.com/">DallyDaydream</a>
                and the characters in those campaigns.</p>
            <p><b>Important: This site may contain spoilers for any of the listed campaigns.
                You have been warned.</b></p>
            <br>
            <p><a class="btn btn-primary btn-lg" href="{% url 'campaign_list' %}" role="button">Campaigns »</a>
                <a class="btn btn-primary btn-lg" target="_blank" href="https://www.youtube.com/channel/UCQqETl88a5aGrM0_vpGo_0Q" role="button">Recordings on YouTube »</a></p>
        </div>
    </div>
{% endblock %}