dally_stats/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', include('smuggler.urls')),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'', include('stally.urls')),
]

mwm-db/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.flatpages import views

urlpatterns = [
    # url(r'^admin/', include('smuggler.urls')),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'', include('apps.database.urls')),
    url(r'^pages/', include('django.contrib.flatpages.urls')),

    # Flatpages
    url(r'^contributor-guidelines-1/$', views.flatpage,
        {'url': '/contributor-guidelines-1/'}, name='guidelines-1'),
    url(r'^contributor-guidelines-2/$', views.flatpage,
        {'url': '/contributor-guidelines-2/'}, name='guidelines-2'),
    url(r'^contributor-guidelines-3/$', views.flatpage,
        {'url': '/contributor-guidelines-3/'}, name='guidelines-3'),
    url(r'^contributor-guidelines-4/$', views.flatpage,
        {'url': '/contributor-guidelines-4/'}, name='guidelines-4'),
]

apps/database/models.py
# This Python file uses the following encoding: utf-8

from django.urls import reverse
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.validators import validate_comma_separated_integer_list
from datetime import timedelta
from .myFields import DayOfTheWeekField


class BaseModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE,
                                   related_name='%(class)s_created',
                                   null=True, blank=True, default=None)
    modified_by = models.ForeignKey(User, on_delete=models.CASCADE,
                                    related_name='%(class)s_modified',
                                    null=True, blank=True, default=None)

    class Meta:
        abstract = True


class Player(BaseModel):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/players/',
                              default='images/no-img.jpg')

    def main_characters(self):
        characters = Character.objects.filter(player=self)
        trainees = Trainee.objects.filter(player=self)
        campaigns = Campaign.objects.filter(dm=self)
        npcs = Character.objects.filter(campaign__in=campaigns)
        return characters.exclude(pk__in=trainees).exclude(pk__in=npcs)

    def __str__(self):
        return self.name

    def __lt__(self, other):
        return self.name < other.name

    def get_absolute_url(self):
        return reverse('player_detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['name']


class Campaign(BaseModel):
    name = models.CharField(max_length=200)
    dm = models.ForeignKey(Player, on_delete=models.PROTECT,
                           related_name='campaigns_dming', verbose_name='DM')
    start_date = models.DateField(default=timezone.now,
                                  verbose_name='Start date')
    image = models.ImageField(upload_to='images/campaigns/',
                              default='images/no-img.jpg')
    youtube_playlist = models.URLField(blank=True, null=True,
                                       verbose_name='YouTube playlist')
    streaming_channel = models.URLField(blank=True, null=True,
                                        verbose_name='Streamed on')
    schedule = DayOfTheWeekField(blank=True, null=True,
                                 verbose_name='Is played on')
    schedule_time = models.TimeField(blank=True, null=True, verbose_name='At')
    schedule_rythm = models.CharField(blank=True, null=True, max_length=1,
                                      choices=(
                                        ('1', 'weekly'),
                                        ('2', 'biweekly'),
                                        ('3', 'every three weeks'),
                                      ))
    genre = models.CharField(blank=True, null=True, max_length=100)
    system = models.CharField(blank=True, null=True, max_length=200)
    description = models.TextField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True,
                                verbose_name='End date')

    def players(self):
        characters = Character.objects.filter(campaign=self)
        return sorted(set(Player.objects.filter(
            characters__in=characters).exclude(name=self.dm.name)))

    def characters_without_trainees(self):
        characters = Character.objects.filter(
            campaign=self).exclude(pk__in=self.npcs())
        trainees = Trainee.objects.filter(campaign=self)

        return characters.exclude(pk__in=trainees)

    def pc_pokemon(self):
        return Pokemon.objects.filter(campaign=self).exclude(player=self.dm)

    def npcs(self):
        characters = Character.objects.filter(campaign=self)
        pokemon = Pokemon.objects.filter(campaign=self)
        return characters.filter(player=self.dm).exclude(pk__in=pokemon)

    def npc_pokemon(self):
        pokemon = Pokemon.objects.filter(campaign=self)
        return pokemon.filter(player=self.dm)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('campaign_detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['name']


class Session(BaseModel):
    name = models.CharField(max_length=200)
    date = models.DateField(default=timezone.now)
    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE,
                                 related_name='sessions')
    length = models.DurationField(default=timedelta(0))
    number = models.IntegerField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    players_present = models.ManyToManyField(Player, blank=True)

    def __str__(self):
        return "{}. {}".format(self.number, self.name)

    class Meta:
        ordering = ['name']


class URL(BaseModel):
    link = models.URLField()
    session = models.ForeignKey(Session, on_delete=models.CASCADE,
                                related_name='youtube_videos')


class Place(BaseModel):
    name = models.CharField(max_length=400)
    campaigns = models.ManyToManyField(Campaign)
    description = models.TextField(blank=True, null=True)


class Character(BaseModel):
    name = models.CharField(max_length=100)
    player = models.ForeignKey(Player, on_delete=models.PROTECT,
                               related_name='characters')
    campaign = models.ForeignKey(Campaign, on_delete=models.PROTECT,
                                 related_name='characters')
    character_class = models.CharField(max_length=200, blank=True, null=True,
                                       verbose_name='Class')
    image = models.ImageField(upload_to='images/characters/',
                              default='images/no-img.jpg')
    pronouns = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    lives_in = models.ManyToManyField(Place, blank=True,
                                      related_name='citizens')
    in_campaign_since = models.ForeignKey(Session, on_delete=models.SET_NULL,
                                          blank=True, null=True)

    def pokemons(self):
        return Pokemon.objects.filter(trainer=self)

    def pets(self):
        return Pet.objects.filter(trainer=self)

    def is_npc(self):
        return self.player == self.campaign.dm

    def __str__(self):
        if self.is_npc():
            return '{} (NPC)'.format(self.name)
        else:
            return '{} (played by {})'.format(self.name, self.player.name)

    def get_absolute_url(self):
        return reverse('character_detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['name']


class Trainee(Character):
    trainer = models.ForeignKey(
        Character, on_delete=models.SET_NULL, related_name='trainees',
        blank=True, null=True)

    class Meta:
        ordering = ['name']


class Pokemon(Trainee):
    pokedex_nr = models.CharField(
        max_length=7, blank=True, null=True,
        validators=[validate_comma_separated_integer_list],
        verbose_name='Pokédex number')
    type_p = models.CharField(max_length=200, verbose_name='Type')
    nature = models.CharField(max_length=200, blank=True, null=True)
    kind = models.CharField(max_length=200)

    def create_pokemon(character, name, pokedex_nr, type_p, nature, kind):
        new_pokemon = Pokemon(name=name, player=character.player,
                              campaign=character.campaign,
                              pokedex_nr=pokedex_nr,
                              trainer=character,
                              type_p=type_p, nature=nature, kind=kind)
        new_pokemon.save()

    def get_absolute_url(self):
        return reverse('pokemon_detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Pokémon'
        verbose_name_plural = 'Pokémon'


class Pet(Trainee):
        def get_absolute_url(self):
            return reverse('pet_detail', kwargs={'pk': self.pk})

templates/base.html
{% load staticfiles %}
{% load tags %}

{% url 'about' as about %}
{% url 'campaign_list' as home %}

<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block pagetitle %}BORKBORKBORK{% endblock %} - Mistakes Were Made...DB</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext">
    <link rel="stylesheet" href="{% static 'css/database.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
</head>

<body>
    <div class="page-header">

        <h1><a href="/">Mistakes Were Made...DB</a></h1>
        <!--<h2>No regrets! ...Okay, a few regrets</h2>-->
        <nav class="navbar">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                        aria-expanded="false">
        				<span class="sr-only">Toggle navigation</span>
        				<span class="icon-bar"></span>
        				<span class="icon-bar"></span>
        				<span class="icon-bar"></span>
        			</button>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav navbar-left">
                      <li class="dropdown">
                          <a href="{{ home }}" class="dropdown-toggle {% active request home %}" data-toggle="dropdown" role="button" aria-haspopup="true"
                              aria-expanded="false">Campaigns<span class="caret"></span></a>
                          <ul class="dropdown-menu">
                              <li><a href="{% url 'campaign_list' %}">Overview</a></li>
                              <li class="divider"></li>
                              {% campaigns_list_items %}
                          </ul>
                      </li>
                      <!--<li><a href="http://www.informatik.uni-oldenburg.de/~lucasn/stream/">
                          Audio Stream</a></li>-->
                      <li><a class="{% active request about %}" href="{{ about }}">About</a></li>
                  </ul>

                  <ul class="nav navbar-nav navbar-right">
                      {% if user.is_authenticated %}
                      <li class="dropdown">
                          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                              aria-expanded="false">New<span class="caret"></span></a>
                          <ul class="dropdown-menu">
                              {% if perms.database.add_character %}
                                <li><a href="{% url 'npc_new' %}" class="">Add NPC</a></li>
                              {% endif %}
                              {% if perms.database.add_character %}
                                <li><a href="{% url 'character_new' %}" class="">Add character</a></li>
                              {% endif %}
                              {% if perms.database.add_pokemon %}
                                <li><a href="{% url 'pokemon_new' %}" class="">Add Pokémon</a></li>
                              {% endif %}
                              {% if perms.database.add_pet %}
                                <li><a href="{% url 'pet_new' %}" class="">Add pet</a></li>
                              {% endif %}
                              {% if perms.database.add_campaign %}
                                <li><a href="{% url 'campaign_new' %}" class="">Add campaign</a></li>
                              {% endif %}
                          </ul>
                      </li>
                      <li class="dropdown">
                          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                              aria-expanded="false">Hello {{ user.username }}<span class="caret"></span></a>
                          <ul class="dropdown-menu">
                              <li><a href="{% url 'guidelines-1' %}">Contributor guidelines</a></li>
                              <li><a href="{% url 'admin:index' %}" class="">Admin</a></li>
                              <li><a href="{% url 'logout' %}" class="">Log out</a></li>
                          </ul>
                      </li>
                    {% else %}
                    <li><a href="{% url 'register' %}" class="top-menu">
                          Create account</a>
                        </li>
                      <li><a href="{% url 'login' %}" class="top-menu">
                            <span class="glyphicon glyphicon-lock glyphicon-small" aria-hidden="true"></span></a>
                          </li>

                    {% endif %}
                  </ul>
            </div>
        </nav>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-9">
                {% block content %} {% endblock %}
            </div>
        </div>
    </div>


    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>

</html>